import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    globals: true,
    environment: 'node',
    include: ['tests/**/*.test.ts'],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'text-summary', 'lcov'],
      include: ['src/**/*.ts'],
      exclude: [
        'src/index.ts',
        'src/db/schema.ts',
        'src/core/logger.ts',
        'src/core/types.ts',
        'src/core/redis.ts',
        'src/**/*.d.ts',
        'src/adapters/**',
        'src/wallet/**',
        'src/data/**',
        'src/helpers/**',
        'src/gateway/**',
        'src/broker/**',
        'src/agent/**',
        'src/trader/jupiter-executor.ts',
        'src/trader/hyperliquid-executor.ts',
        'src/trader/oneinch-executor.ts',
        'src/trader/zerox-executor.ts',
        'src/trader/order-executor.ts',
        'src/trader/gas-manager.ts',
        'src/trader/types.ts',
        'src/core/ws-client.ts',
        'src/core/ws-gateway.ts',
        'src/core/ws-hub.ts',
        'src/core/orchestrator.ts',
        'src/api/server.ts',
        'src/api/routes/**',
        'src/supervisor/supervisor.ts',
        'src/supervisor/agent-registry.ts',
        'src/supervisor/approval-engine.ts',
        'src/supervisor/hibernation-manager.ts',
        'src/supervisor/policy-engine.ts',
        'src/supervisor/types.ts',
      ],
    },
    testTimeout: 10_000,
    hookTimeout: 10_000,
  },
  resolve: {
    alias: {
      '@': '/src',
    },
  },
});
